---

- name: "Ensure certmanager is {{ certmanager_state }}"
  kubernetes.core.helm:
    kubeconfig: "{{ certmanager_kubeconfig }}"
    name: cert-manager
    chart_repo_url: "https://charts.jetstack.io"
    chart_ref: cert-manager
    release_namespace: "{{ certmanager_namespace }}"
    release_state: "{{ certmanager_state }}"
    chart_version: "{{ certmanager_chart_version }}"
    create_namespace: true
    wait: false
    values:
      installCRDs: true
  become_user: "{{ ansible_user }}"

- name: Wait till certmanager is running
  tags: notest
  kubernetes.core.k8s_info:
    kind: Deployment
    wait: true
    name: "{{ item }}"
    namespace: "{{ certmanager_namespace }}"
    wait_sleep: 30
    wait_timeout: 360
  loop:
    - cert-manager
    - cert-manager-cainjector
    - cert-manager-webhook
  become_user: "{{ ansible_user }}"
  when: certmanager_state == "present"
