---

- name: Verify
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Assure certmanager is installed
    kubernetes.core.helm:
      name: cert-manager
      chart_repo_url: "https://charts.jetstack.io"
      chart_ref: cert-manager
      release_namespace: default
      release_state: present
    register: result
  - name: Assure cert-manager is installed
    ansible.builtin.assert:
      that: 
      - result.status.status == "deployed"
